### PR TITLE
Fixes layout for overview page

### PR DESCRIPTION
**Pull request by ekhomyakova**

### CODE REVIEW

**Comment by naumvd95** [comment]
@ekhomyakova how it should looks like?

**Comment by ekhomyakova** [comment]
@naumvd95 there will be 2 tabs, for clusters and provisioners. 
So if the list of clusters will be very long, then provisioners will be still accessible with ease.

**Comment by naumvd95** [comment]
If so, LG for me, but pls provide screen proofs here
thanks in advance

**Comment by ekhomyakova** [comment]
image
image

**Pull request merged**
