### PR TITLE
[WIP] Refactoring

### PR DESCRIPTION
**Pull request by ekhomyakova**

### CODE REVIEW

**Comment by naumvd95** [comment]
@ekhomyakova  pls provide valid description in commit/PR body to clarify short summary

**Comment by naumvd95** [comment]
@ekhomyakova and seems we have 1 more broken test after your changes, can u check? travis link above^^

**Comment by katyafervent** [comment]
Looks nice! I suggest to separate this commit by topics and describe changes in commit messages: documentation improvements, html reformatting, small bug fixing and etc.

**Comment by atengler** [comment]
Thanks for the refactoring, I realize, that our JS and some HTML templates are in sorry state. Just two points though, we don't require strict PEP line length, so you don't really have to make the lines in python shorter (I don't mind if you do though, if the readability imporves). And secondly, from my understanding, arrow functions in JS are not supported by any version of IE, just in Edge, is it worth using while losing compatibility with IE?

**Pull request closed without merging**
