### PR TITLE
Fixes for cluster details page

### PR DESCRIPTION
**Pull request by ekhomyakova**
- remove redundant ul/li
- make statuses more user-friendly

### CODE REVIEW

**Comment by naumvd95** [comment]
resolve conflicts manually pls

**Comment by ekhomyakova** [comment]
That's how it looks like now.
image

**Comment by naumvd95** [comment]
@ekhomyakova do we have logging levels in Statuses from api?
i mean is it possible to highlight errors/warnings with red color and any others with green?
anyway LG for me

**Comment by ekhomyakova** [comment]
@naumvd95 we have `status` which can be True or False. If it's False, then the labels are green, otherwise, they are red

**Pull request merged**
