### PR TITLE
Enable tooltip help-messages on forms

### PR DESCRIPTION
**Pull request by katyafervent**
Useful information and links can be provided
during form filling.

### CODE REVIEW

**Comment by katyafervent** [comment]
screenshot from 2018-06-19 07-07-01

**Comment by naumvd95** [comment]
@katyafervent @b-zone 
maybe its better to write shadow-like-tips directly in empty field?
image

**Comment by katyafervent** [comment]
You can use placeholder for that, for a small text, but for detailed description (with links) placeholder would not work

**Comment by naumvd95** [comment]
in that case i prefer smth like '?' button to get links and docs, coz imo this tips overload page

**Pull request closed without merging**
